# Generated by Django 3.1.3 on 2021-01-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('postal_code', models.CharField(max_length=31)),
                ('country', models.CharField(max_length=63)),
            ],
            options={
                'unique_together': {('address', 'city', 'postal_code', 'country')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1023)),
                ('phone_number', models.CharField(max_length=15)),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heapp.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heapp.organizationtypes')),
                ('staff', models.ManyToManyField(to='heapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1023)),
                ('is_positive', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heapp.feedback')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heapp.organization')),
                ('participants', models.ManyToManyField(to='heapp.User')),
                ('tags', models.ManyToManyField(to='heapp.Tag')),
            ],
        ),
    ]
