# Generated by Django 3.1.3 on 2021-01-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localization',
            unique_together=set(),
        ),
    ]
